### PR TITLE
feat: support custom robots content or disable tags

### LINKED ISSUE #749: Support custom `robots` and `googlebot` content
# Description

In certain situations a developer might prefer passing a string to robots tags, or disabling the meta tag entirely.

# Solution

Add a `robots` property and set meta tag content via string, or disable meta tags complete.

# Alternatives

None that I can think of.

### PR DESCRIPTION
**Pull request by dgrebb**
# Description

Added a `robots` property which will either pass the meta tags' `content` via string (and include `robotsProps` if set), or disable the meta tags entirely.

Fixes #749

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

Tested within the project as well as locally via patching as well as `pnpm i /system-path/to/svelte-meta-tags` in local project.

- [x] `pnpm test`
- [x] manually via `pnpm build && pnpm preview`

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by oekazuma** [comment]
Thanks for your contribution!

We already have properties to control `noindex` and `nofollow`, but is that not enough?

**Comment by dgrebb** [comment]
@oekazuma to each their own. In my particular situation my SEO is controlled via fields in a CMS. In this case, both `noindex` and `nofollow` are passed as one string to the `content` attribute. Splitting up the CMS fields is a no-can do.

I'm fine with patching this myself but wanted to throw it out there in case it ever comes up :)

Cheers!

**Comment by oekazuma** [comment]
I am looking to support a variety of use cases. However, we are concerned that adding a `robots` property would complicate the properties that affect the robots element.

I'm still struggling with what to do, but I'm wondering if integrating the `robots` feature with the `robotsProps` feature might be a solution?

**Comment by dgrebb** [comment]
@oekazuma understood. Closing this for now, and will find some time to change things around in a separate PR.

Thank you for the feedback!

**Pull request closed without merging**
